service:
  name: io_control_service

comm_core:
  endpoint: tcp://127.0.0.1:5555

driver:
  service_name: modbus_driver_service

# ชื่อ service กลางที่รับ push_data และส่งคำสั่งกลับมา
# (ถ้าในระบบพี่ชื่อ uplink_service ก็แก้ตรงนี้ได้)
platform_integrator:
  service_name: uplink_service

polling:
  interval_sec: 0.5
  driver_timeout_ms: 2000

reporting:
  interval_sec: 5
  include_on_no_change: true

log:
  level: INFO
  log_modbus_hex: false

rtu_devices:
  - name: io8ch_1
    slave_id: 1
    baudrate: 9600
    parity: N
    stopbits: 1
    bytesize: 8
    timeout: 0.5
    ensure_normal_mode_on_startup: true
    di_priority: [low, low, low, low, low, low, low, low]

  - name: io8ch_2
    slave_id: 2
    baudrate: 9600
    parity: N
    stopbits: 1
    bytesize: 8
    timeout: 0.5
    ensure_normal_mode_on_startup: true
    di_priority: [low, low, low, low, low, low, low, low]

  - name: io8ch_3
    slave_id: 3
    baudrate: 9600
    parity: N
    stopbits: 1
    bytesize: 8
    timeout: 0.5
    ensure_normal_mode_on_startup: true
    di_priority: [low, low, low, low, low, low, low, low]

  - name: io8ch_4
    slave_id: 4
    baudrate: 9600
    parity: N
    stopbits: 1
    bytesize: 8
    timeout: 0.5
    ensure_normal_mode_on_startup: true
    di_priority: [low, low, low, low, low, low, low, low]
